import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    height: "68%",
    width: "100%",
    backgroundColor: "#fff",
    borderRadius: 25,
    position: "absolute",
    bottom: 0,
    borderBottomRightRadius: 0,
    borderBottomLeftRadius: 0,
    alignItems: "center",
    justifyContent: "center",
    flex: 2,
  },
  image: {
    position: "absolute",
    // top: "-30%",
    top: -100,
    left: "37.5%",
    //  marginBottom: 32,
    width: 120,
    height: 120,
    borderRadius: 16,
    backgroundColor: "#f6f6f6",
  },
  mainContainer: {
    width: "100%",
    padding: 16,
    alignItems: "center",
    justifyContent: "center",
    // gap: 16,
    textAlign: "center",
    position: "relative",
  },
  textInput: {
    width: "100%",
    backgroundColor: "#f6f6f6",
    borderWidth: 1,
    borderColor: "#e8e8e8",
    borderRadius: 8,
    height: 50,
    paddingHorizontal: 16,
    fontFamily: "Regular",
    //  position: "relative",
    // paddingBottom: 15,
  },
  formContainer: {
    width: "100%",
    // gap: 16,
    //  position: "relative",
  },
  title: {
    marginBottom: 33,
    color: "#212121",
    fontSize: 30,
    fontFamily: "Medium",
  },
  btn: {
    width: "100%",
    height: 51,
    backgroundColor: "#ff6c00",
    borderRadius: 100,
    marginTop: 43,
    justifyContent: "center",
    alignItems: "center",
    // paddingVertical: 16,
    // paddingHorizontal: 111.5,
  },
  btnText: {
    color: "#fff",
    fontSize: 16,
    fontFamily: "Regular",
  },
  loginText: {
    width: "100%",
    color: "#1b4371",
    fontSize: 16,
    marginTop: 16,
    textAlign: "center",
    fontFamily: "Regular",
  },
  show: {
    width: 72,
    color: "#1b4371",
    fontSize: 16,
    top: 15,
    right: 16,
    position: "absolute",
    fontFamily: "Regular",
  },
  passwordInputCont: {
    position: "relative",
  },
  add: {
    position: "absolute",
    left: 107,
    top: 81,
  },
});
